<?php

namespace App\Support;

use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithHeadings;

class QuestionImportTemplateExport implements FromArray, ShouldAutoSize, WithHeadings
{
    public function headings(): array
    {
        return [
            'order_number',
            'type',
            'question_text',
            'score_weight',
            'explanation',
            'stimulus_key',
            'stimulus_title',
            'stimulus_type',
            'stimulus_content',
            'option_a',
            'option_b',
            'option_c',
            'option_d',
            'option_e',
            'correct_answer',
            'statement_positive_label',
            'statement_negative_label',
            'statement_rows',
            'is_active',
        ];
    }

    public function array(): array
    {
        return [
            [
                1,
                'multiple_choice',
                'Ide pokok paragraf tersebut adalah ...',
                10,
                'Fokus pada kalimat utama di awal paragraf.',
                'BAC01',
                'Bacaan 1',
                'text',
                'Bacalah paragraf berikut untuk menjawab soal nomor 1 dan 2.',
                'Kegiatan gotong royong mempererat persaudaraan.',
                'Kegiatan gotong royong hanya dilakukan di sekolah.',
                'Kegiatan gotong royong menambah pekerjaan warga.',
                'Kegiatan gotong royong membuat lingkungan kotor.',
                '',
                'A',
                '',
                '',
                '',
                '1',
            ],
            [
                2,
                'multiple_choice_complex',
                'Pilih semua pernyataan yang sesuai dengan bacaan.',
                10,
                'Boleh lebih dari satu jawaban benar.',
                'BAC01',
                'Bacaan 1',
                'text',
                'Bacalah paragraf berikut untuk menjawab soal nomor 1 dan 2.',
                'Warga bekerja sama membersihkan selokan.',
                'Lingkungan menjadi lebih nyaman.',
                'Warga saling cuek satu sama lain.',
                'Gotong royong hanya merugikan warga.',
                '',
                'A|B',
                '',
                '',
                '',
                '1',
            ],
            [
                3,
                'true_false',
                'Kalimat tersebut termasuk kalimat efektif.',
                5,
                'Periksa struktur subjek dan predikat.',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                'Benar',
                '',
                '',
                '',
                '1',
            ],
            [
                4,
                'true_false_group',
                'Tentukan Tepat atau Tidak Tepat untuk setiap pernyataan berikut.',
                15,
                'Setiap baris harus dipilih salah satu kolom.',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                'Tepat',
                'Tidak Tepat',
                'Kalimat 1 sesuai isi bacaan::1 | Kalimat 2 bertentangan dengan bacaan::0 | Kalimat 3 tidak didukung data::0',
                '1',
            ],
            [
                5,
                'essay',
                'Jelaskan manfaat kerja sama di lingkungan sekolah.',
                20,
                'Nilai esai diberikan admin setelah ujian selesai.',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '',
                '1',
            ],
        ];
    }
}
